In [1]:
!pip install biopython

Collecting biopython
  Downloading biopython-1.88-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from biopython) (2.1.3)
Downloading biopython-1.88-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 44.2 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.88

In [2]:
from Bio import SeqIO
from Bio.SeqUtils import gc_fraction

In [3]:
records = list(SeqIO.parse('insulin_human.fasta', 'fasta'))

print(f"Number of sequences: {len(records)}")

Number of sequences: 2

In [4]:
for r in records:
    print(f"ID: {r.id}")
    print(f"Length: {len(r.seq)}")
    print(f"GC: {gc_fraction(r.seq) * 100:.2f}%")
    print(f"Sequence: {str(r.seq[:50])}...")
    print("-" * 50)

ID: NC_000011.10:c2161209-2159779
Length: 1431
GC: 64.64%
Sequence: AGCCCTCCAGGACAGGCTGCATCAGAAGAGGCCATCAAGCAGGTCTGTTC...
--------------------------------------------------
ID: NC_060935.1:c2248857-2247427
Length: 1431
GC: 64.71%
Sequence: AGCCCTCCAGGACAGGCTGCATCAGAAGAGGCCATCAAGCAGGTCTGTTC...
--------------------------------------------------

In [5]:
import pandas as pd

summary = []

for r in records:
    summary.append({
        'ID': r.id,
        'Length': len(r.seq),
        'GC (%)': gc_fraction(r.seq) * 100
    })

df = pd.DataFrame(summary)

df

                              ID  Length     GC (%)
0  NC_000011.10:c2161209-2159779    1431  64.640112
1   NC_060935.1:c2248857-2247427    1431  64.709993

In [6]:
df = pd.DataFrame(summary)

In [7]:
print("\nSummary Table:")
display(df)

Summary Table:

                              ID  Length     GC (%)
0  NC_000011.10:c2161209-2159779    1431  64.640112
1   NC_060935.1:c2248857-2247427    1431  64.709993